### ISSUE TITLE
White, empty interface

### ISSUE THREAD

**Issue by amirography** [klauscfhq/tusk#81]
Hi all. 
![screenshot_20180510_104917](https://user-images.githubusercontent.com/28535608/39855107-d0c23492-543f-11e8-9ee9-360eada6586f.png)
As you can see, tusk is showing a white space.
When I use terminal to run Tusk these come up: 
```
[am@awesomebook ~]$ "/opt/Tusk/tusk-app" %U
{ Error: Cannot find module '../tray'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/opt/Tusk/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as Tray] (/opt/Tusk/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at Object.exports.create.win [as create] (/opt/Tusk/resources/app.asar/tray.js:129:22)
    at App.app.on (/opt/Tusk/resources/app.asar/index.js:112:10)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7) code: 'MODULE_NOT_FOUND' }
[am@awesomebook ~]$ 

```
I'm running on antergos, KDE desktop, and tried both 0.10.1 (still available on AUR) and version 0.11.0.

**Comment by klauscfhq** [comment]
Looks a lot like a connectivity issue, try pressing <kdb>Ctrl</kdb> + <kdb>R</kdb> to reload, hopefully that will resolve it.

**Comment by klauscfhq** [comment]
Closing, for now, will reopen if needed in the future.
